require 'yaml'
require 'pry'
require 'rest-client'
require 'json'
require_relative '../app/runners/cli'
require_relative '../app/data_fetchers/intrinio'
require_relative '../app/data_fetchers/scraper'
require_relative '../app/models/intrinio_model'
